### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by tuansondinh** [p2o-lab/polaris-backend#216]
**Describe the bug**
We have a problem with circular dependencies, which we should avoid, because they could lead to unexpected behavior and crashes.

**To Reproduce**
example: new InputElement(...) will lead to creash while compiling
(Go to InputElement.spec.ts to try it out)

**Expected behavior**
should compile

**Screenshots**
![image](https://user-images.githubusercontent.com/62188772/125082058-0318c200-e0c7-11eb-9a8d-54c975ce5a75.png)

I am using madge package here to find out circular dependencies

**Comment by julorenz** [comment]
madge --circular --extensions ts ./src
madge --circular --image graph.svg --extensions ts ./src

is helpful

for now avoided through explicit creation of ParameterRequest as standalone class
