### ISSUE TITLE
Instantiate of VirtualService failes

### ISSUE THREAD

**Issue by Martin-Seemann** [p2o-lab/polaris-backend#75]
**Describe the bug**
After the ModuleTestServer were added 2 times with the names PEA1 and PEA2, the instantiate of the Aggregated Services with this PEAs failes with the message "TypeError: Cannot read property 'find' of undefined".

**To Reproduce**
1. Add Module "ModuleTestServer" 2 times as "PEA1" and "PEA2" (from assets)
2. Try to instantiate an AggregatedService for the ModuleTestServer (from assets)
3. The Error occures after click on "Instantiate"

**Expected behavior**
The Virtual Service should instantiate correctly and be displayed in the overview

**Desktop**
 - OS: [Windows 7 x64]
 - Browser [Firefox]
 - Version [69.0.3]

**Comment by markusgraube** [comment]
thank you for this issue. I have found the bug and I am working on a fix
